### ISSUE TITLE
 No module named 'bblfsh.gopkg' for v2.12.2

### ISSUE THREAD

**Issue by zurk** [bblfsh/client-python#131]
```python
import bblfsh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/bblfsh/__init__.py", line 1, in <module>
    from bblfsh.client import BblfshClient
  File "/usr/local/lib/python3.5/dist-packages/bblfsh/client.py", line 6, in <module>
    from bblfsh.aliases import (ParseRequest, NativeParseRequest, VersionRequest,
  File "/usr/local/lib/python3.5/dist-packages/bblfsh/aliases.py", line 11, in <module>
    "bblfsh.gopkg.in.bblfsh.sdk.%s.uast.generated_pb2" % VERSION)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'bblfsh.gopkg'
```

**Comment by vmarkovtsev** [comment]
Indeed, no proto bindings exist in the new package @juanjux

**Comment by juanjux** [comment]
Frag, forgot to run getdeps, will fix it.

**Comment by juanjux** [comment]
Fixed in v2.12.3 already on pypi.

**Comment by zurk** [comment]
Incredible speed!

**Comment by juanjux** [comment]
Incredible speed because this is not the first time I have made this error...
