### ISSUE TITLE
[bug] Attribute error on ctx.get_all()

### ISSUE THREAD

**Issue by alichtman** [bblfsh/client-python#146]
Running this snippet produces the following error:

```python
def process_embeddings(code: str):
	client = bblfsh.BblfshClient("0.0.0.0:9432")
	ctx = client.parse("arbitrary.java", language="java", contents=str.encode(code))
	print(ctx)
	print("Type of ctx:", type(ctx))
	resdict = ctx.get_all()
	return resdict
```

`ctx` prints as expected, but the type seems to be incorrect, which causes an `Attribute Error` to be thrown.

The parse method signature is: `def parse(self, filename: str, language: Optional[str]=None, contents: Optional[str]=None, mode: Optional[ModeType]=None, timeout: Optional[int]=None) -> ResultContext:`

I was expecting the type to be `ResultContext`, but `type(ctx)` produced `<class 'gopkg.in.bblfsh.sdk.v1.protocol.generated_pb2.ParseResponse'>`.

I think this is the root cause of the Attribute Error, but I was unable to debug the issue further.

```
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    main()
    └ <function main at 0x11558c268>
  File "main.py", line 188, in main
    feature_set = extract_features(submissions)
                  │                └                                                     code                 author
0              public static void doNothing() {\...
                  └ <function extract_features at 0x1029fb048>
  File "main.py", line 50, in extract_features
    metrics, new_docSpace_additions = extract_metrics(code)
                                      │               └ 'public static void doNothing() {\n    \n}'
                                      └ <function extract_metrics at 0x10b60d840>
  File ".../controller.py", line 63, in extract_metrics
    metrics['embeddings'] = process_embeddings(code)
    │                       │                  └ 'public static void doNothing() {\n    \n}'
    │                       └ <function process_embeddings at 0x114a77d90>
    └ {'identifiers': {'raw_identifiers': [], 'identifier_freq': Counter(), 'is_camel_caser': True, 'num_unique_identifiers': 0, 'avg_...
  File ".../embeddings.py", line 14, in process_embeddings
    resdict = ctx.get_all()
              └ elapsed {
  nanos: 10864400
}
uast {
  internal_type: "CompilationUnit"
  children {
    internal_type: "TypeDeclaration"
    pr...
AttributeError: get_all
```

**Comment by dennwc** [comment]
Related to v1 API. See [examples](https://github.com/bblfsh/client-python/blob/master/README.md#usage) for the currently supported v2.
