### ISSUE TITLE
Python driver causes error during deserialization

### ISSUE THREAD

**Issue by r0mainK** [bblfsh/client-python#93]
This might be linked to [issue 89](https://github.com/bblfsh/client-python/issues/89), when I looked for this kind of error on slack I found a thread from. couple days ago where Egor had this issue, and  @smola referenced it. However after looking at it, I do not think it is the same, given it seems to concern JavaScript files. 

## Context

Was trying to run `apollo` bags on 4G of files, specified languages the following languages: `Bash`, `Java`, `Python`, `Ruby`, then during deserialization I got this error log:

```
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/usr/local/lib/python3.4/dist-packages/sourced/ml/transformers/basic.py", line 186, in deserialize_uast
  File "/usr/local/lib/python3.4/dist-packages/sourced/ml/transformers/basic.py", line 186, in <listcomp>
google.protobuf.message.DecodeError: Error parsing message

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.next(PythonRDD.scala:156)
	at org.apache.spark.api.python.PythonRunner$$anon$1.next(PythonRDD.scala:152)
	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsBytes(MemoryStore.scala:372)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1055)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.api.python.PairwiseRDD.compute(PythonRDD.scala:395)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The error popped at [this](https://github.com/src-d/ml/commit/99a3ec3f84f5e43d5676f51e0b52d3b080850317#diff-370750368c8314a487dfbae4ca854901R186) line), as you can see a fix has already been implemented to circumvent this for now but still.

Since I had not seen this error before, I tried to specify only one language at a time to see if it was a driver problem. After trials, was surprised to see it was the Python driver that caused this (surprised because when doing tests on another batch of siva files where i know there where Python files, this error did not pop up). When looking in the executor logs, I found these kind of errors logs:

```
18/04/04 14:11:56 WARN Bblfsh: FATAL os/src/shell/micropython/tests/pyboard.py: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/python_driver/requestprocessor.py", line 139, in process_request
    '\n------ Python3 errors:\n%s' % codeinfo['py3_ast_errors']
Exception: Errors produced trying to get an AST for both Python versions
------ Python2 errors:
[b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\n  File "/usr/lib/python2.7/site-packages/pydetector/ast2dict.py", line 19, in ast2dict\n    return visitor.parse()\n  File "/usr/lib/python2.7/site-packages/pydetector/ast2dict.py", line 45, in parse\n    tree = ast.parse(self.codestr, mode=\'exec\')\n  File "/usr/lib/python2.7/ast.py", line 37, in parse\n    return compile(source, filename, mode, PyCF_ONLY_AST)\n  File "<unknown>", line 1\n    ../tools/pyboard.py\n    ^\nSyntaxError: invalid syntax\n']
------ Python3 errors:
['Traceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/pydetector/ast_checks.py", line 53, in check_ast\n    current_ast = ast2dict(code)\n  File "/usr/lib/python3.6/site-packages/pydetector/ast2dict.py", line 19, in ast2dict\n    return visitor.parse()\n  File "/usr/lib/python3.6/site-packages/pydetector/ast2dict.py", line 45, in parse\n    tree = ast.parse(self.codestr, mode=\'exec\')\n  File "/usr/lib/python3.6/ast.py", line 35, in parse\n    return compile(source, filename, mode, PyCF_ONLY_AST)\n  File "<unknown>", line 1\n    ../tools/pyboard.py\n    ^\nSyntaxError: invalid syntax\n']
```

So yeah, don't have much more info then this,  this is not insanely urgent as we have a workaround at the moment, but still pretty annoying.

**Comment by juanjux** [comment]
The last error is normal, meaning that the file is broken and neither Python2 or 3 AST module could parse it. Should not cause spark to fail.

The error above certainly could be related with issue #89 since it seems to be an error deserializing a protobuf message (not really a python client error but we're investigating it).
